apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000  # Port exposed on the service within the cluster
      targetPort: 5000  # Port your Flask app is listening on inside the pod
  type: NodePort
